#pragma once

#ifdef VULPESENGINE_EXPORTS
#define VULPESENGINE_CLASS __declspec(dllexport)
#else
#define VULPESENGINE_CLASS __declspec(dllimport)
#endif


typedef struct tagVPE_PARAM_VALUE {
	int nx;
	int ny;
	float fx;
	float fy;
} VPE_PARAM_VALUE;


enum VPE_IMAGE_RESULT
{
	IMAGE_RESULT_SRC = 0x100000,
	IMAGE_RESULT_AM = 0x0001,
	IMAGE_RESULT_MAX_ACCUM_AM = 0x0002,
	IMAGE_RESULT_AVG_ACCUM_AM = 0x0004,
	IMAGE_RESULT_MIN_ACCUM_AM = 0x0008,
	IMAGE_RESULT_BASE_DELTA_AM = 0x0010,
	IMAGE_RESULT_FAST_DELTA_AM = 0x0020,

	IMAGE_RESULT_FREQ = 0x0100,
	IMAGE_RESULT_MAX_ACCUM_FREQ = 0x0200,
	IMAGE_RESULT_AVG_ACCUM_FREQ = 0x0400,
	IMAGE_RESULT_MIN_ACCUM_FREQ = 0x0800,
	IMAGE_RESULT_BASE_DELTA_FREQ = 0x1000,
	IMAGE_RESULT_FAST_DELTA_FREQ = 0x2000,

	IMAGE_RESULT_MASK_SRC = (IMAGE_RESULT_AM | IMAGE_RESULT_FREQ | IMAGE_RESULT_SRC),
	IMAGE_RESULT_MASK_AM = 0x00FF,
	IMAGE_RESULT_MASK_FREQ = 0xFF00,
	IMAGE_RESULT_MASK_DELTA = (IMAGE_RESULT_BASE_DELTA_AM | IMAGE_RESULT_BASE_DELTA_FREQ),
	IMAGE_RESULT_CONTOUR_AROUD = (IMAGE_RESULT_AM | IMAGE_RESULT_FREQ)
};


enum VPE_PARAM {
	RESET,
	START,
	STOP,
	PAUSE,
	FRAME_IN,
	FRAME_OUT,
	FRAME_BASE,
	FRAME_FAST,
	FRAME_DROP,

	MAX_ACCUM_FRAME,
	AVG_ACCUM_FRAME,
	MIN_ACCUM_FRAME,
	MAX_ACCUM_FRAME_SET,
	AVG_ACCUM_FRAME_SET,
	MIN_ACCUM_FRAME_SET,

	FPS_IN,
	FPS_OUT,
	FPS_OUT_BASE,
	FPS_OUT_FAST,
	FPS_DROP_BASE,
	FPS_DROP_FAST,
	FPS_MAX_BASE,
	FPS_MAX_FAST,
	FPS_PERIOD,

	FILTER_GAIN_FACTOR,
	FILTER_BRIGHT_THRESHOLD,
	FILTER_FPS_DIVISION,
	FILTER_FPS_DIVISION_SET,
	FILTER_FPS_REDUCE_RATE,
	FILTER_AUTO_REDUCE_RATE,
	FILTER_HF_THRESHOLD,
	FILTER_LF_THRESHOLD,
	FILTER_PERIOD_THRESHOLD,
	FILTER_HISTOGRAM_CV,
	FILTER_CONTOUR,
	FILTER_CONTOUR_MAX_SPEED,
	FILTER_STRETCH,
	FILTER_EXTEND_THRESHOLD,
	FILTER_EXTEND_FAST_THRESHOLD,
	FILTER_AM,
	FILTER_SPACE,
	FILTER_SINGLE_POINTS,
	FILTER_CROP,
	FILTER_CROP_POSITION,
	FILTER_DISTORTION,
	FILTER_STAB_X,
	FILTER_STAB_Y,
	FILTER_SKIP,
	FILTER_SKIP_FRAME,
	FILTER_MOTION,
	FILTER_MOTION_SET,
	FILTER_MOTION_INTERGRATE_AVG_ACCUM,
	FILTER_MOTION_LEVEL,
	FILTER_MOTION_AUTO_RESET,
	FILTER_HISTNW,
	FILTER_DISABLE_AM,
	FILTER_DISABLE_FREQ,
	FILTER_DISABLE_FAST,
	FILTER_DISABLE_MAX_ACCUM,
	FILTER_DISABLE_AVG_ACCUM,
	FILTER_DISABLE_MIN_ACCUM,
	FILTER_DISABLE_FFT,
	FILTER_DISABLE_ENTROPY,

	CRITICAL_FLAG,
	CRITICAL_LEVEL,
	CRITICAL_LEVEL_RANGE,
	CRITICAL_LEVEL_GRADE,
	CRITICAL_MODE_FAST_LEVEL,
	CRITICAL_MODE_FAST_AREA_RATE,
	CRITICAL_FREQ_FFT_FAST_LEVEL,
	CRITICAL_MAX_ACCUM_CV_RANGE_LEVEL,
	CRITICAL_MAX_ACCUM_CV_HISTOGRAM_LEVEL,

	MODE_FAST_ENABLE,
	MODE_FAST_FACE_ENABLE,
	MODE_BASE_ENABLE,
	MODE_BG_COLOR,
	MODE_IMAGE_RESULT,
	MODE_IMAGE_SIZE,
	MODE_IMAGE_COLOR,
	MODE_FAST_CONTOUR_AROUD,
	MODE_BASE_CONTOUR_AROUD,

	STATEMENT_PERIOD,
	STATEMENT_PERIOD_BASE,
	STATEMENT_ENABLE,
	STATEMENT_STARTED,
	STATEMENT_LTH,
	STATEMENT_MODE,
	STATEMENT_MODE_OPPOSITE,
	STATEMENT_MODE_TEXT,
	STATEMENT_MODE_CMP,

	FACE_DETECT_ENABLE,
	FACE_DETECT_CONFIG_FILE,
	FACE_DETECT_DRAW,
	FACE_DETECT_QUALITY,
	FACE_DETECT_SCALE,
	FACE_DETECT_QUALITY_SIZE_MIN,
	FACE_DETECT_QUALITY_SIZE_MAX,
	FACE_DETECT_INFO,

	STAT_CFG_SIN,
	STAT_CFG_HISTFN,

	CORRELATION_ENABLE,
	CORRELATION_MEDIAN,
	CORRELATION_TSTAT,
	CORRELATION_TSHIFT1,
	CORRELATION_TSHIFT2,
	CORRELATION_TAUTO,
	CORRELATION_X,
	CORRELATION_Y,
	CORRELATION_HIPASS,
	CORRELATION_LOPASS,
	CORRELATION_AVG,
	CORRELATION_MAKE_T,

	HISTOGRAM_FAST_FFT_READY,
	HISTOGRAM_MAX_ACCUM_AM_AVG,
	HISTOGRAM_MAX_ACCUM_FREQ_AVG,
	HISTOGRAM_AVG_ACCUM_AM_AVG,
	HISTOGRAM_AVG_ACCUM_FREQ_AVG,
	HISTOGRAM_MIN_ACCUM_AM_AVG,
	HISTOGRAM_MIN_ACCUM_FREQ_AVG,
	HISTOGRAM_MAX_ACCUM_AM_BASE,
	HISTOGRAM_MAX_ACCUM_FREQ_BASE,
	HISTOGRAM_AVG_ACCUM_AM_BASE,
	HISTOGRAM_AVG_ACCUM_FREQ_BASE,
	HISTOGRAM_MIN_ACCUM_AM_BASE,
	HISTOGRAM_MIN_ACCUM_FREQ_BASE,
	HISTOGRAM_MAX_ACCUM_AM_FAST,
	HISTOGRAM_MAX_ACCUM_FREQ_FAST,
	HISTOGRAM_AVG_ACCUM_AM_FAST,
	HISTOGRAM_AVG_ACCUM_FREQ_FAST,
	HISTOGRAM_MIN_ACCUM_AM_FAST,
	HISTOGRAM_MIN_ACCUM_FREQ_FAST,
	HISTOGRAM_FREQ_PERIOD_TIME_AVG,
	HISTOGRAM_FREQ_PERIOD_TIME_DELTA,
	HISTOGRAM_MAX_ACCUM_AM_BASE_AVG,
	HISTOGRAM_AVG_ACCUM_AM_BASE_AVG,
	HISTOGRAM_MIN_ACCUM_AM_BASE_AVG,
	HISTOGRAM_MAX_ACCUM_FREQ_BASE_AVG,
	HISTOGRAM_AVG_ACCUM_FREQ_BASE_AVG,
	HISTOGRAM_MIN_ACCUM_FREQ_BASE_AVG,

	STAT_RESULT_START,
	STAT_RESULT_AM_INTEGRATE_MAX_ACCUM,
	STAT_RESULT_AM_INTEGRATE_AVG_ACCUM,
	STAT_RESULT_AM_INTEGRATE_MIN_ACCUM,
	STAT_RESULT_FREQ_INTEGRATE_MAX_ACCUM,
	STAT_RESULT_FREQ_INTEGRATE_AVG_ACCUM,
	STAT_RESULT_FREQ_INTEGRATE_MIN_ACCUM,
	STAT_RESULT_CRITICAL_LEVEL,
	STAT_RESULT_AM_FAST,
	STAT_RESULT_AM,
	STAT_RESULT_AVG_AM,
	STAT_RESULT_AVG_ACCUM_AM,
	STAT_RESULT_MAX_ACCUM_AM,
	STAT_RESULT_AVG_AM_FAST,
	STAT_RESULT_FREQ,
	STAT_RESULT_FREQ_FAST,
	STAT_RESULT_FREQ_DELTA,
	STAT_RESULT_AVG_ACCUM_FREQ,
	STAT_RESULT_MAX_ACCUM_FREQ,
	STAT_RESULT_MAX_ACCUM_FREQ_MAX,
	STAT_RESULT_FREQ_FFT,
	STAT_RESULT_FREQ_FFT_FAST,
	STAT_RESULT_FREQ_PERIOD_TIME_AVG,
	STAT_RESULT_FREQ_PERIOD_TIME_SD,
	STAT_RESULT_FREQ_PERIOD_TIME_DELTA,
	STAT_RESULT_FREQ_PERIOD_TIME_CV,
	STAT_RESULT_MIN_ACCUM_AM_CV_VALUE_RATE,
	STAT_RESULT_MIN_ACCUM_AM_CV_NUM_RATE,
	STAT_RESULT_AVG_ACCUM_AM_CV_VALUE_RATE,
	STAT_RESULT_AVG_ACCUM_AM_CV_NUM_RATE,
	STAT_RESULT_MAX_ACCUM_AM_CV_VALUE_RATE,
	STAT_RESULT_MAX_ACCUM_AM_CV_NUM_RATE,
	STAT_RESULT_MAX_ACCUM_AM_CV_DIFFERENCE,
	STAT_RESULT_AVG_ACCUM_FREQ_RMSD,
	STAT_RESULT_AVG_ACCUM_FREQ_SCALE,
	STAT_RESULT_MAX_ACCUM_FREQ_RMSD,
	STAT_RESULT_MAX_ACCUM_FREQ_SCALE,
	STAT_RESULT_STATEMENT_CRITICAL,
	STAT_RESULT_MAX_ACCUM_CV_RANGE,
	STAT_RESULT_MAX_ACCUM_AM_CV_RANGE,
	STAT_RESULT_MAX_ACCUM_FREQ_CV_RANGE,
	STAT_RESULT_MAX_ACCUM_CV_HISTOGRAM,
	STAT_RESULT_MAX_ACCUM_AM_CV_HISTOGRAM,
	STAT_RESULT_MAX_ACCUM_FREQ_CV_HISTOGRAM,
	STAT_RESULT_MAX_ACCUM_HISTOGRAM_RMSD,
	STAT_RESULT_MAX_ACCUM_AM_HISTOGRAM_RMSD,
	STAT_RESULT_MAX_ACCUM_FREQ_HISTOGRAM_RMSD,
	STAT_RESULT_MAX_ACCUM_HISTOGRAM_LOG_RMSD,
	STAT_RESULT_MAX_ACCUM_AM_HISTOGRAM_LOG_RMSD,
	STAT_RESULT_MAX_ACCUM_FREQ_HISTOGRAM_LOG_RMSD,
	STAT_RESULT_MAX_ACCUM_HISTOGRAM_ENTROPY,
	STAT_RESULT_MAX_ACCUM_AM_HISTOGRAM_ENTROPY,
	STAT_RESULT_MAX_ACCUM_FREQ_HISTOGRAM_ENTROPY,
	STAT_RESULT_MAX_ACCUM_HISTOGRAM_RSD,
	STAT_RESULT_MAX_ACCUM_AM_HISTOGRAM_RSD,
	STAT_RESULT_MAX_ACCUM_FREQ_HISTOGRAM_RSD,
	STAT_RESULT_MAX_ACCUM_HISTOGRAM_LOG_RSD,
	STAT_RESULT_MAX_ACCUM_AM_HISTOGRAM_LOG_RSD,
	STAT_RESULT_MAX_ACCUM_FREQ_HISTOGRAM_LOG_RSD,
	STAT_RESULT_HIST_CRITICAL_VALUE_RATE,
	STAT_RESULT_HIST_CRITICAL_CNT_RATE,
	STAT_RESULT_HIST_ALL_CNT_RATE,
	STAT_RESULT_MAX_ACCUM_FREQ_HISTOGRAM_SD,
	STAT_RESULT_MAX_ACCUM_AM_HISTOGRAM_DIFFERENCE,
	STAT_RESULT_MAX_ACCUM_FREQ_AM_HISTOGRAM_AVG,
	STAT_RESULT_CRITICAL,
	STAT_RESULT_CRITICAL_AVG,
	STAT_RESULT_STATEMENT_QUANTITY_INDICATOR,
	STAT_RESULT_CRITICAL_HEALTH_ONCOLOGY,
	STAT_RESULT_CRITICAL_HEALTH_PG,
	STAT_RESULT_CRITICAL_HEALTH_AVG,
	STAT_RESULT_AM_HISTOGRAM_DIFFERENCE_NORMALIZE,
	STAT_RESULT_MAX_ACCUM_FREQ_NORMALIZE,
	STAT_RESULT_CRITICAL_HEALTH_EXTRAVERSION,
	STAT_RESULT_CRITICAL_HEALTH_STABILITY,
	STAT_RESULT_MAX_ACCUM_FREQ_STATISFY,
	STAT_RESULT_CRITICAL_HEALTH_DEPRESSION,
	STAT_RESULT_CRITICAL_HEALTH_HAPPINESS,
	STAT_RESULT_SIN,
	STAT_RESULT_FAST_PIX_MIDDLE_CV,
	STAT_RESULT_FAST_PIX_MIDDLE_CV_DELTA,
	STAT_RESULT_FAST_PIX_BOTH_CV,
	STAT_RESULT_FAST_PIX_BOTH_CV_DELTA,
	STAT_RESULT_FAST_PIX_CV,
	STAT_RESULT_END,
	PARAM_CNT
};


class VULPESENGINE_CLASS CVulpesEngine
{
public:
	CVulpesEngine(int nThread);
	~CVulpesEngine();


public:
	int AddFrameImage(void* pucImage, int nWidth, int nHeight, int nBpp, double dTime);
	int IsSrcMaskSet();
	void GetFilter(int nParamId, int n, float* psf, float* pff, BOOL* pbHP, BOOL* pbEN);
	int GetHistogramStat(int nParamId, int* pnHistogram, float* pfFPS);
	int GetHistogramFFTStat(int nParamId, int* pnHistogram, float* pfFPS);
	int GetHistogramSumStat(int id, float* px, float* py);
	int GetContour(int* pnLeftSumCV, int* pnRightSumCV, int* pnLeftMaxCV, int* pnRightMaxCV, int nMode, int bFlag);
	float GetAverage(int nParamId, int* pnCnt);
	float GetCorrelation(int nParamId1, int nParamId2, float* pfValue, int* pnSize);
	void GetParamValueF(int nParamId, float& fx, float& fy);
	float GetParamValueFx(int nParamId);
	float GetParamValueFy(int nParamId);
	void GetParamValueN(int nParamId, int& nx, int& ny);
	int	GetParamValueNx(int nParamId);
	int GetParamValueNy(int nParamId);
	VPE_PARAM_VALUE GetParamValue(int nParamId);
	int GetResultImageSrc(int* pnWidth, int* pnHeight, void* pucImage);
	float* GetResultImageCV(int n);
	int GetResultImageData(int nImageResultId, void** pucImage, int* pnWidth, int* pnHeight);
	int GetResultImageRegionLine(int nLineWidth, int nLineHeight, float* pfLineWidthData, float* pfLineHeightData);
	RGBQUAD* GetRgbPal();
	int GetStatMaxMin(int nParamId, float* pfCalculateMin, float* pfCalculateMax, float* pfBaseMin, float* pfBaseMax, float* pfRate, int* pnBaseRate);
	int GetStatCalculateStatus(int nParamId);
	float GetStatLevel(int nParamId);
	float GetStatLevelDef(int nParamId);
	float GetStatRate1(int nParamId);
	float GetStatRate1def(int nParamId);
	float GetStatRate1v(int nParamId);
	float GetStatRate2(int nParamId);
	float GetStatRate2def(int nParamId);
	float GetStatRate2v(int nParamId);
	void* GetStoreCapture();
	int GetStoreCaptureParamData(int nParamId, double dTime, double* pdData, VPE_PARAM_VALUE* pValue);
	double GetStoreCaptureDataLength(void* pStoreCapture);
	VPE_PARAM_VALUE* GetStoreCaptureParamValue(VPE_PARAM_VALUE* pValue, int nParamId, double dTime);
	void* LockResult(int nLock, void* pLock);

	void Reset();
	void Pause(int nStatus);
	void SetCallbackOnAddFrameImage(void* pFunction, void* pData);
	void SetCallbackOnParamData(void* pFunction, void* pData);
	void SetFilter(int nParamId, int n, float sf, float ff, BOOL bHP, BOOL bEN);
	void SetFpsMultiple(float fValue);
	void SetFpsSpeed(float fValue);
	void SetParamAverage(int nParamId, int nCnt);
	void SetParamAverage(int nParamId, int nCnt, float fValue);
	void SetParamValue(int nParamId, VPE_PARAM_VALUE& pValue);
	void SetParamValueF(int nParamId, float fx, float fy);
	void SetParamValueFx(int nParamId, float fx);
	void SetParamValueFy(int nParamId, float fy);
	void SetParamValueN(int nParamId, int nx, int ny);
	void SetParamValueNx(int nParamId, int x);
	void SetParamValueNy(int nParamId, int y);
	void SetParamValueStr(int nParamId, LPCWSTR lpStr);
	void SetRgbPal(RGBQUAD* pal);
	int SetResultImageData(int nImageResultId, void* pucImage, int nWidth, int nHeight);
	int SetSrcMaskErase(int nWidth, int nHeight);
	int SetSrcMaskLoad(LPCWSTR lpStr);
	int SetSrcMaskSave(LPCWSTR lpStr);
	void SetStatCalculateStatus(int nParamId, int nCalc);
	void SetStatLevel(int nParamId, float fValue);
	void SetStatRate1(int nParamId, float fValue);
	void SetStatRate1v(int nParamId, float fValue);
	void SetStatRate2(int nParamId, float fValue);
	void SetStatRate2v(int nParamId, float fValue);
	void SetStoreCaptureErase(void* pStoreCapture);
	void SetStoreCaptureStart();
	void SetStoreCaptureStop();
	void Start();
	void Stop(int nFlag);;

};